### ISSUE TITLE
Nuxt 3 DevTools CSS Overflow

### ISSUE THREAD

**Issue by ThatOneRockyBoy** [nuxt/devtools#414]
### Environment

Nuxt project info:                                                                                                                      12:12:23

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules, css
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -
------------------------------

### Reproduction

Always

### Describe the bug

When enabling dev tools and setting a background makes the page overflow.

When setting scss to this:
```scss
html,
body,
#__nuxt {
  @apply w-full h-full;
}

body {
  background-image: url('/images/background.jpg');
  @apply bg-neutral-800 bg-cover bg-center backdrop-blur-sm bg-no-repeat bg-fixed;
}

```

It overflows the page and adds a scrollbar.

![image](https://github.com/nuxt/nuxt/assets/135866417/b31569f4-60e9-435f-92c4-35c116c741cb)

I could just disable the dev tools sure but it would be nice if it didn't affect my own styling.

**Comment by arashsheyda** [comment]
@ThatOneRockyBoy applying `backdrop-blur` on parent(body) is breaking the child position somehow, a workaround that comes to my mind is:
```scss
body {
  background-image: url('/images/background.jpg');
  @apply bg-neutral-800 bg-cover bg-center bg-no-repeat bg-fixed;

  &::before {
    @apply content-empty inset-0 z--1 absolute backdrop-blur
  }
}
```

<details>
<summary>with backdrop-filter on body::before :</summary>

![image](https://github.com/nuxt/devtools/assets/38922203/a228d12d-f1da-4324-9edc-a007c18d25f1)

</details>

<details>
<summary>with backdrop-filter on body :</summary>

![image](https://github.com/nuxt/devtools/assets/38922203/80d66a0a-7b3e-4c0f-9df3-32b83fd8b85d)

</details>
